# Generated by Django 5.0 on 2024-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
                ('Description', models.CharField(max_length=200)),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
